# Generated by Django 4.1.1 on 2022-09-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('fullname', models.CharField(max_length=100)),
                ('twitter_link', models.URLField()),
                ('facebook_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('youtube_link', models.URLField()),
                ('cv', models.FileField(upload_to='files')),
                ('phone_number', models.CharField(max_length=13)),
            ],
        ),
    ]
