# Generated by Django 4.1.1 on 2022-09-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='skill',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
