# Generated by Django 4.1.1 on 2022-09-28 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0002_customer_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateTimeField()),
                ('experience', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('freelance', models.CharField(max_length=50)),
            ],
        ),
    ]
