# Generated by Django 4.1.1 on 2022-09-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expericence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmer', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('info', models.TextField()),
            ],
        ),
    ]
