# Generated by Django 4.1.1 on 2022-10-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0009_categories_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img/testimonial/')),
                ('body', models.TextField()),
            ],
        ),
    ]
