# Generated by Django 4.1.1 on 2022-10-02 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0011_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_contact',
        ),
    ]
