# Generated by Django 4.1.1 on 2022-10-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0012_rename_email_contact_email_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='freelance',
            new_name='salary',
        ),
        migrations.RemoveField(
            model_name='about',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='about',
            name='body',
        ),
        migrations.RemoveField(
            model_name='about',
            name='name',
        ),
    ]
