# Generated by Django 4.1.1 on 2022-10-04 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0013_rename_freelance_about_salary_remove_about_birthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='body',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
