# Generated by Django 4.1.1 on 2022-10-04 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0014_about_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('images', models.ImageField(blank=True, null=True, upload_to='images_programming/')),
            ],
        ),
        migrations.AlterField(
            model_name='skills',
            name='programm',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='skills',
            name='progress',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='development_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='homeapp.development'),
        ),
    ]
