# Generated by Django 4.1.1 on 2022-10-06 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0015_development_alter_skills_programm_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='development',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
